import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function ContentLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="bg-[#F6F6F6] min-h-screen flex flex-col">
            <Navbar />
            <div className="flex flex-grow">
                <div className="w-52 bg-white">
                    <Sidebar />
                </div>
                <div className="flex-grow px-12 pt-36 pb-14">
                    {children}
                </div>
            </div>
        </div>
    );
}
